### ISSUE TITLE
Error tag 2.10.0

### ISSUE THREAD

**Issue by jlanza** [mytestbed/oml4py#1]
Line 103:
    uri_l = uri.split(":")

It has one extra level of identation. That makes the package installed from using pip or downloading from OML site works incorrectly. This is solved in 2.11pre

```
File "/usr/local/lib/python2.7/dist-packages/oml4py.py", line 105, in __init__
    if len(uri_l) == 1:     # host
UnboundLocalError: local variable 'uri_l' referenced before assignment
```

**Comment by ghost** [comment]
This is fixed in the 2.10.1 release.
